src/BlogJob/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^posts/', include("posts.urls", namespace="posts")),
]

src/posts/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import (
		post_list,
		post_create,
		post_update,
		post_detail,
		post_delete,
	)

urlpatterns = [
	url(r'^$', post_list),
    url(r'^create/$', post_create, name="create"),
    url(r'^update/$', post_update),
    url(r'^(?P<id>\d+)/$', post_detail, name="detail"),
    url(r'^(?P<id>\d+)/edit/$', post_update, name="update"),
    url(r'^delete/$', post_delete),
]

src/posts/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
# MVC- Model, View, Controller

class Post(models.Model):
	title = models.CharField(max_length=120)
	content = models.TextField()
	updated = models.DateTimeField(auto_now = True, auto_now_add = False) #set whenever the fields are updated
	timestamp = models.DateTimeField(auto_now = False, auto_now_add = True) #set when the field is initialized

	#the difference between python2 and python3 
	def __unicode__(self):
		return self.title

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("posts:detail", kwargs={"id":self.id})

src/posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = [
			'title',
			'content'
		]

src/posts/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.core.urlresolvers import reverse
from .models import Post
from .forms import PostForm
# Create your views here.

def post_update(request, id=None, *args, **kwargs):
	obj = get_object_or_404(Post, id=id)
	title = "Edit"
	form = PostForm(request.POST or None, instance=obj)
	if form.is_valid():
		form.save()
		redirect('reverse("posts:detail", kwargs={"id":self.id})')
	context = {
		"form" : form,
		"title" : title,
		"object" : obj
	}
	return render(request, "post_update.html", context)

def post_create(request, *args, **kwargs):
	form = PostForm(request.POST or None)
	context = {
		"form" : form
	}
	if form.is_valid():
		form.save()
		form = PostForm()
		context = {
			"form":form,
			"message" : "The post was successfully created"
		}
	return render(request, "post_create.html", context)

def post_detail(request, id, *args, **kwargs):
	obj = get_object_or_404(Post, id=id)
	context = {
		"title" : "Detail",
		"instance": obj,
	}
	return render(request, "post_detail.html", context)

def post_list(request, *args, **kwargs):
	queryset = Post.objects.all()
	context = {
		"title" : "Lists",
		"object_list" : queryset,
	}
	return render(request, "index.html", context)

def post_delete(request, *args, **kwargs):
	return HttpResponse("<h1>Delete</h1>")

src/templates/index.html
<html>
<head>
	<title>Index Page</title>
</head>
<body>
	<h1>{{title}}</h1>
	{% for instance in object_list %}
		<br/><a href='{% url "posts:update" id=instance.id %}'>Edit</a><br/>
		{% url "posts:detail" id=instance.id %}<br/>
		<a href='{{ instance.get_absolute_url }}' >{{instance.id}}</a><br/>
		<a href='{{ instance.get_absolute_url }}' >{{instance.title}}</a><br/>
		{{instance.content}}<br/>
		{{instance.updated}}<br/>
		{{instance.timestamp}}<br/>
	{% endfor %}
</body>
</html>

src/templates/post_create.html
<form method="POST"> {% csrf_token %}
	{{form.as_p}}
	<input type="submit" value="Save">
</form>
<div>
	{% if message %}
		<h4>{{message}}</h4>
	{% endif%}
</div>

src/templates/post_detail.html
<html>
<head>
	<title>Index Page</title>
</head>
<body>
	<h1>{{title}}</h1>
	{{instance.id}}<br/>
	{{instance.title}}<br/>
	{{instance.content}}<br/>
	{{instance.updated}}<br/>
	{{instance.timestamp}}<br/>
</body>
</html>

src/templates/post_update.html
<h2>{{ title }}</h2>
<form method="POST"> {% csrf_token %}
	{{form.as_p}}
	<input type="submit" value="Save">
</form>